### PR TITLE
TV: Use onFailureClosure for request limits (#222)

### LINKED ISSUE #222: broadcast: on request limit excession we should disable broadcast
We don't currently handle the case when we don't have any more request tokens left i.e. we have exceeded the YT request limit. This means we get a start failed event, but try again the next time. Instead we should probably use the onFailureClosure which can disable the broadcast.

### PR DESCRIPTION
**Pull request by ao-david**
When a ErrRequestLimitExceeded error is received from svc.CreateBroadcast we will use the disable on first failure bool in the failure closure to ensure the broadcast is disabled before making any additional calls to youtube (which will also be rate limited). This will prevent us from extending our broadcast down time by needlessly making blocked calls, adding to our rate limit.

closes #222

### CODE REVIEW

**Review by trekhopton — APPROVED** [review]

**Comment by saxon-milton** [comment]
Only thing I'd say about this one is that we could try and add testing with
it (think we should get into this habit with broadcast stuff). Not sure
what exactly this would look like though. Might have to add a mock limiter
to the mock broadcast service.

Cheers,
Saxon

**Comment by davidsutts** [comment]
> Only thing I'd say about this one is that we could try and add testing with it (think we should get into this habit with broadcast stuff). Not sure what exactly this would look like though. Might have to add a mock limiter to the mock broadcast service.

Yeah I did briefly have a look at this. I will try and implement a mock limiter.

**Comment by ao-david** [comment]
@saxon-milton added testing (and a mock limiter)

File: cmd/oceantv/broadcast_test.go [hunk 1]
```diff
@@ -388,3 +407,15 @@ func (bus *mockEventBus) checkEvents(want []event) error {
 	}
 	return nil
 }
+
+type mockLimiter struct {
```
Comment (saxon-milton) [inline cmd/oceantv/broadcast_test.go:411]: I think there's a mock.go file that can house all mock stuff.

**Review by saxon-milton — APPROVED** [review]
