### PR TITLE
Bench: Fix Navmenu on configure page (#344)

### LINKED ISSUE #344: bench: init is undefined on configure page.
init is undefined on the device's configure page which means the navigation menu won't work.

Work around is edit the url to go where you want to go.

### PR DESCRIPTION
**Pull request by ao-david**
This change fixes the nav menu by ensuring the common data Page field is initialised correctly. This change also adds field validation for the configure page.

closes #344

### CODE REVIEW

File: cmd/oceanbench/s/configure.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
+function init() {
```
Comment (ao-david) [inline cmd/oceanbench/s/configure.js:1]: This is for the bootstrap form validation: https://getbootstrap.com/docs/5.0/forms/validation/

**Review by trekhopton — APPROVED** [review]
