### PR TITLE
bench: isolate scalar tests

### LINKED ISSUE #542: bench: TestGetScalars fails on main when run locally
```
--- FAIL: TestGetScalars (1.23s)
    data_test.go:96: TestGetScalars
    data_test.go:112: Expected 86400 scalars, got 569
    data_test.go:119: #0: expected 512, got 355.000000
    data_test.go:119: #1: expected 513, got 354.000000
    data_test.go:119: #2: expected 514, got 353.000000
...
data_test.go:119: #565: expected 672, got 507.000000
    data_test.go:119: #566: expected 671, got 508.000000
    data_test.go:119: #567: expected 670, got 509.000000
    data_test.go:119: #568: expected 669, got 510.000000
panic: runtime error: index out of range [569] with length 569 [recovered]
        panic: runtime error: index out of range [569] with length 569

goroutine 59 [running]:
testing.tRunner.func1.2({0xd5cbc0, 0xc00003fb90})
        /home/trek/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
        /home/trek/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/testing/testing.go:1635 +0x35e
panic({0xd5cbc0?, 0xc00003fb90?})
        /home/trek/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/runtime/panic.go:785 +0x132
github.com/ausocean/cloud/cmd/oceanbench.TestGetScalars(0xc0004d61a0)
        /home/trek/go/src/github.com/ausocean/cloud/cmd/oceanbench/data_test.go:118 +0x3ed
testing.tRunner(0xc0004d61a0, 0xe24f78)
        /home/trek/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
        /home/trek/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.4.linux-amd64/src/testing/testing.go:1743 +0x390
FAIL    github.com/ausocean/cloud/cmd/oceanbench        116.735s
```

Sometimes it takes a crazy amount of time to test too. 473s.

### PR DESCRIPTION
**Pull request by trekhopton**
This was done to make them more reliable and not depend on others tests. This means the get and fetch tests will take longer, but to fix that we could do a multi put.

Closes #542

### CODE REVIEW

File: .gcloudignore [hunk 1]
```diff
@@ -54,4 +54,9 @@ cmd/vidforward/#*
...
 cmd/ausoceantv/.gitignore
 cmd/ausoceantv/node_modules/
-cmd/ausoceantv/webapp/node_modules/
\ No newline at end of file
+cmd/ausoceantv/webapp/node_modules/
+
+cmd/decode/*
+cmd/cloudblue/*
+cmd/oceancast/*
+cmd/roadmap/*
```
Comment (ao-david) [inline .gcloudignore:62]: do we not want to commit this?

**Review by ao-david — APPROVED** [review]
This needs a rebase before merging, as I think that commits from a different change have made their way in. But otherwise LGTM

File: .gcloudignore (hunk 1 above)
Comment (trekhopton) [reply .gcloudignore:62]: No harm in adding to the ignore file I think. I know they're experimental projects that aren't on main but my thinking was, why not add them? It helps me deploy more cleanly because I don't want to get rid of some of those project folders.

File: cmd/oceanbench/data_test.go [hunk 2]
```diff
@@ -67,27 +67,42 @@ func TestPutScalars(t *testing.T) {
...
+			Value:     float64(samples[i]),
+		})
 		if err != nil {
 			t.Errorf("PutScalar failed with error: %v", err)
 		}
 		ts += 60
+
+		// Print progress every 10%.
+		if i%(minutesInDay/10) == 0 {
+			t.Logf("put %d/%d scalars", i, minutesInDay)
```
[the remark this answers is not in the document]
Comment (trekhopton) [reply cmd/oceanbench/data_test.go:104]: Because this is a long running test, I think it's useful, it only results in 10 logs since it only does 10% increments, that's fine IMO.
