### PR TITLE
Bench: Add reset button (#582)

### LINKED ISSUE #582: OTV: Reset hardwareFailure state in broadcast via UI
It seems that the HSM gets stuck in HardwareFailure state and toggling "failure mode" in the UI to off doesn't solve the issue. 

This is an important issue because it means when a broadcast failure due to a hardware failure, someone has to go into the datastore to manually edit the broadcast.. not good.

We just get an error when the broadcast tries to restart: unexpected event startBroadcastRequestEvent in state hardwareFailure:

Image

I propose a reset button that resets the BSM and HSM states so the broadcast can try again from a clean slate.

### PR DESCRIPTION
**Pull request by ao-david**
This change adds a reset state button to the broadcast UI which will allow the user to reset the state of a broadcast without breaking any other values.
closes #582 
image

### CODE REVIEW

**Comment by saxon-milton** [comment]
> This change adds a reset state button to the broadcast UI which will allow the user to reset the state of a broadcast without breaking any other values. closes #582 image

Should we call it "Reset States" so that it corresponds to both ?

File: cmd/oceantv/main.go [hunk 1]
```diff
@@ -47,7 +47,7 @@ import (
 
 const (
 	projectID          = "oceantv"
-	version            = "v0.10.7"
+	version            = "v0.10.8"
```
Comment (saxon-milton) [inline cmd/oceantv/main.go:50]: This probably actually a minor bump

File: cmd/oceanbench/broadcast.go [hunk 2]
```diff
@@ -435,6 +436,23 @@ func broadcastHandler(w http.ResponseWriter, r *http.Request) {
 
 		}
 		msg = "slate uploaded successfully"
+	case broadcastResetState:
+		log.Println("Sending Reset State Req")
```
Comment (trekhopton) [inline cmd/oceanbench/broadcast.go:440]: Lowercase for log messages.

Comment (trekhopton) [reply cmd/oceanbench/broadcast.go:440]: Use full words too, not "Req".

**Review by saxon-milton — APPROVED** [review]

**Review by trekhopton — APPROVED** [review]
